pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                bat 'echo "Olá Build"'
            }
        }
        stage('Deploy') {
            steps {
                bat 'echo "Olá Deploy"'
            }
        }
    }
}